### ISSUE TITLE
Build  an Alexa conversation Skill with Python and Azure Functions

### ISSUE THREAD

**Issue by filippoalberi** [sjwaight/AzureNewsOnAlexa#1]
hi, 
is it possible to create a backend of an alexa conversation skill using this procedure with azure and ngrock with python?
thanks everyone.

**Comment by sjwaight** [comment]
Yes, that's what the code in this repo does (you only need ngrok for local debugging). Have a read of the [blog post](https://blog.siliconvalve.com/2021/08/31/how-to-build-and-debug-an-alexa-skill-with-python-and-azure-functions/) for more information.
